spring:
  config:
    activate:
      on-profile: localhost
  application:
    name: local-laboratory

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: UTC
    generate-ddl: false

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:~/laboratory
      username: laboratory
      password: laboratory
      driver-class-name: org.h2.Driver
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      maxLifetime: 580000
      connectionTimeout: 10000
      pool-name: laboratory-server

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 1995
  shutdown: immediate


